name: Build webOS IPK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # تم التحديث إلى v4

      - name: Set up Node.js
        uses: actions/setup-node@v4 # تم التحديث إلى v4
        with:
          node-version: '20' # استخدام نسخة Node حديثة ومستقرة

      - name: Install webOS CLI
        run: npm install -g @webos-tools/cli

      - name: Package App
        run: |
          mkdir -p build
          ares-package . -o ./build

      - name: Upload Artifact
        uses: actions/upload-artifact@v4 # تم التحديث إلى v4 لحل مشكلة الصورة الثانية
        with:
          name: webos-package
          path: build/*.ipk
